### ISSUE TITLE
Plugin approval

### ISSUE THREAD

**Issue by NyakudyaA** [AntonioTLeandro/Numerar_Lotes#1]
# Problem
Please change plugin homepage link to https://github.com/AntonioTLeandro/Numerar_Lotes/tree/main

**Comment by AntonioTLeandro** [comment]
Ploblem fixed

I tried to correct it directly in the plugin but l couldn't, so l uploaded
it again.


Atenciosamente.


Em qua., 13 de jul. de 2022 às 08:12, mazano ***@***.***>
escreveu:

**Comment by NyakudyaA** [comment]
LGTM

**Comment by NyakudyaA** [comment]
Side note: There is also this plugin https://plugins.qgis.org/plugins/HouseNumbering/ which was highly used. Is the functionality with your very different ?

**Comment by AntonioTLeandro** [comment]
And different, what I developed, it numbers sequentially or taking the size
of the tested, always clockwise, the functionality and numbering standard
allotments for now, I intend to make updates to other types of allotments.

Atenciosamente.


Em qua., 13 de jul. de 2022 às 10:32, mazano ***@***.***>
escreveu:

**Comment by AntonioTLeandro** [comment]
Good afternoon, how are you?

I uploaded a new version, but it was not approved. I also did not receive any notification of a problem. Could there be a problem with this new version? How is the validation of plugins working? Is there a time frame for it to be approved?
